In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip --quiet install ijson
!pip --quiet install -U weaviate-client

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.2/119.2 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 330.4/330.4 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 223.8/223.8 kB 19.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 61.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.7/319.7 kB 29.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.17.1 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 5.29.3 which is incompatible.

In [ ]:
%env WEAVIATE_URL=
%env WEAVIATE_API_KEY=

In [ ]:
from huggingface_hub import InferenceClient

client = InferenceClient(token="")

In [ ]:
import json # For reading json file
import ijson # For reading json file
import pandas as pd
from pathlib import Path
import numpy as np
from typing import List
import weaviate
from weaviate.classes.init import Auth
from weaviate.util import generate_uuid5
from weaviate.classes.query import MetadataQuery
import weaviate.classes as wvc
import weaviate.classes.query as wq
import os
import weaviate.classes.config as wc
from sentence_transformers import SentenceTransformer, util
import torch

weaviate_url = os.environ["WEAVIATE_URL"]
weaviate_api_key = os.environ["WEAVIATE_API_KEY"]

# Connect to Weaviate Cloud
client = weaviate.connect_to_weaviate_cloud(
    cluster_url=weaviate_url,
    auth_credentials=Auth.api_key(weaviate_api_key),
)

print(client.is_ready())

True

# BioASQ task B

In [ ]:
with open('/content/drive/MyDrive/BioASQ/BioASQ-training12b/training12b_new.json') as f:
    data = json.load(f)

In [ ]:
# Use pd.json_normalize to convert the JSON to a DataFrame
df = pd.json_normalize(data['questions'],
                     meta=['body','documents','ideal_answer','exact_answer','concepts','type','id','snippets' ])

In [ ]:
# if column exact_answer is Nan get value from column ideal_answer
df['exact_answer'] = df['exact_answer'].fillna(df['ideal_answer'])
df = df.rename(columns={'body': 'question'})

In [ ]:
# Check unique value in _body and _type columns
print(df['_body'].unique())
print(df['_type'].unique())

[nan 'What does Retapamulin treat?' '"DPM1001"'
 'What is the effect of the venom of the cone snail, Conus tulip?'
 'Which are the main genes of formative pluripotency?'
 'To what chromosome would the MKKS gene for McKusick-Kaufman(AKA Kaufman-McKusick) syndrome be found?'
 'Which kinase does ??? inhibit?'
 'Is autism thought to be related to the gene for vasopressin?'
 'What are the symptoms of an incidental durotomy (ID)' 'epiregulin'
 'Where does B type Natriuretic Protein, BNP usually originate from?'
 'What is RT001?'
 'Which one was the first fragment-derived drug to be approved by the US Federal Drug Administration (FDA)?'
 'Is OXLUMO (lumasiran) used for the treatment of primary hyperoxaluria'
 'What process does orexin/hypocretin neurons regulate']
[nan 'yesno' 'summary' 'list' 'factoid']

In [ ]:
print(df['question'].unique().all())

What disease can be treated with Glofitamab?

In [ ]:
#drop _body and _type columns
df = df.drop(columns=['_body', '_type'])

In [ ]:
# plot body and answer
print(df['question'][1])
print(df['ideal_answer'][1])

List signaling molecules (ligands) that interact with the receptor EGFR?
['The 7 known EGFR ligands  are: epidermal growth factor (EGF), betacellulin (BTC), epiregulin (EPR), heparin-binding EGF (HB-EGF), transforming growth factor-α [TGF-α], amphiregulin (AREG) and epigen (EPG).']

In [ ]:
df.head(5)

,question,documents,ideal_answer,concepts,type,id,snippets,triples,exact_answer,temp
0,Is Hirschsprung disease a mendelian or a multi...,"[http://www.ncbi.nlm.nih.gov/pubmed/15858239, ...","[Coding sequence mutations in RET, GDNF, EDNRB...",[http://www.disease-ontology.org/api/metadata/...,summary,55031181e9bde69634000014,"[{'offsetInBeginSection': 131, 'offsetInEndSec...",NaN,"[Coding sequence mutations in RET, GDNF, EDNRB...",Is Hirschsprung disease a mendelian or a multi...
1,List signaling molecules (ligands) that intera...,"[http://www.ncbi.nlm.nih.gov/pubmed/23959273, ...",[The 7 known EGFR ligands are: epidermal grow...,[http://amigo.geneontology.org/cgi-bin/amigo/t...,list,55046d5ff8aee20f27000007,"[{'offsetInBeginSection': 1085, 'offsetInEndSe...",[{'p': 'http://purl.uniprot.org/core/encodedBy...,"[[epidermal growth factor], [betacellulin], [e...",List signaling molecules (ligands) that intera...
2,Is the protein Papilin secreted?,"[http://www.ncbi.nlm.nih.gov/pubmed/3320045, h...","[Yes, papilin is a secreted protein]",NaN,yesno,54e25eaaae9738404b000017,"[{'offsetInBeginSection': 1085, 'offsetInEndSe...",NaN,yes,Is the protein Papilin secreted?0 [Codin...
3,Are long non coding RNAs spliced?,"[http://www.ncbi.nlm.nih.gov/pubmed/22955988, ...",[Long non coding RNAs appear to be spliced thr...,[http://www.nlm.nih.gov/cgi/mesh/2014/MB_cgi?f...,yesno,535d292a9a4572de6f000003,"[{'offsetInBeginSection': 546, 'offsetInEndSec...",NaN,yes,Are long non coding RNAs spliced?0 [Codi...
4,Is RANKL secreted from the cells?,"[http://www.ncbi.nlm.nih.gov/pubmed/22948539, ...",[Receptor activator of nuclear factor κB ligan...,"[http://www.uniprot.org/uniprot/TNF11_RAT, htt...",yesno,55262a9787ecba3764000009,"[{'offsetInBeginSection': 114, 'offsetInEndSec...",NaN,yes,Is RANKL secreted from the cells?0 [Codi...

In [ ]:
# Concat question and ideal_answer and into a new column "temp"
# Check dataframe if exist duplicate "temp"
df['temp'] = df['question'] + str(df['ideal_answer'])
print(df['temp'].duplicated().sum())

0

In [ ]:
# Get question, documents, snippets and ideal answera and save to train dataframe
df = df[['question', 'documents', 'snippets', 'ideal_answer']]

In [ ]:
# Check if exist Nan value
df.isnull().sum()

question        0
documents       0
snippets        0
ideal_answer    0
dtype: int64

In [ ]:
# Plots snippets
df['snippets'][0]

[{'offsetInBeginSection': 131,
  'offsetInEndSection': 358,
  'text': 'Hirschsprung disease (HSCR) is a multifactorial, non-mendelian disorder in which rare high-penetrance coding sequence mutations in the receptor tyrosine kinase RET contribute to risk in combination with mutations at other genes',
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15829955',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 554,
  'offsetInEndSection': 992,
  'text': "In this study, we review the identification of genes and loci involved in the non-syndromic common form and syndromic Mendelian forms of Hirschsprung's disease. The majority of the identified genes are related to Mendelian syndromic forms of Hirschsprung's disease. The non-Mendelian inheritance of sporadic non-syndromic Hirschsprung's disease proved to be complex; involvement of multiple loci was demonstrated in a multiplicative model",
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15617541',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 397,
  'offsetInEndSection': 939,
  'text': 'Coding sequence mutations in e.g. RET, GDNF, EDNRB, EDN3, and SOX10 lead to long-segment (L-HSCR) as well as syndromic HSCR but fail to explain the transmission of the much more common short-segment form (S-HSCR). Furthermore, mutations in the RET gene are responsible for approximately half of the familial and some sporadic cases, strongly suggesting, on the one hand, the importance of non-coding variations and, on the other hand, that additional genes involved in the development of the enteric nervous system still await their discovery',
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/12239580',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 941,
  'offsetInEndSection': 1279,
  'text': 'For almost all of the identified HSCR genes incomplete penetrance of the HSCR phenotype has been reported, probably due to modifier loci. Therefore, HSCR has become a model for a complex oligo-/polygenic disorder in which the relationship between different genes creating a non-mendelian inheritance pattern still remains to be elucidated',
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/12239580',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 129,
  'offsetInEndSection': 358,
  'text': ' Hirschsprung disease (HSCR) is a multifactorial, non-mendelian disorder in which rare high-penetrance coding sequence mutations in the receptor tyrosine kinase RET contribute to risk in combination with mutations at other genes.',
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15829955',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 851,
  'offsetInEndSection': 1007,
  'text': ' The inheritance of Hirschsprung disease is generally consistent with sex-modified multifactorial inheritance with a lower threshold of expression in males.',
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/6650562',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 131,
  'offsetInEndSection': 359,
  'text': 'Hirschsprung disease (HSCR) is a multifactorial, non-mendelian disorder in which rare high-penetrance coding sequence mutations in the receptor tyrosine kinase RET contribute to risk in combination with mutations at other genes.',
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15829955',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 0,
  'offsetInEndSection': 131,
  'text': 'Differential contributions of rare and common, coding and noncoding Ret mutations to multifactorial Hirschsprung disease liability.',
  'beginSection': 'title',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/20598273',
  'endSection': 'title'},
 {'offsetInBeginSection': 0,
  'offsetInEndSection': 210,
  'text': 'BACKGROUND: RET is the major gene associated to Hirschsprung disease (HSCR) with differential contributions of its rare and common, coding and noncoding mutations to the multifactorial nature of this pathology.',
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/21995290',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 151,
  'offsetInEndSection': 376,
  'text': 'In the etiology of Hirschsprung disease various genes play a role; these are: RET, EDNRB, GDNF, EDN3 and SOX10, NTN3, ECE1, Mutations in these genes may result in dominant, recessive or multifactorial patterns of inheritance.',
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15858239',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 0,
  'offsetInEndSection': 83,
  'text': "Chromosomal and related Mendelian syndromes associated with Hirschsprung's disease.",
  'beginSection': 'title',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/23001136',
  'endSection': 'title'},
 {'offsetInBeginSection': 715,
  'offsetInEndSection': 818,
  'text': "The majority of the identified genes are related to Mendelian syndromic forms of Hirschsprung's disease",
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15617541',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 151,
  'offsetInEndSection': 375,
  'text': 'In the etiology of Hirschsprung disease various genes play a role; these are: RET, EDNRB, GDNF, EDN3 and SOX10, NTN3, ECE1, Mutations in these genes may result in dominant, recessive or multifactorial patterns of inheritance',
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15858239',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 417,
  'offsetInEndSection': 615,
  'text': 'On the basis of a skewed sex-ratio (M/F = 4/1) and a risk to relatives much higher than the incidence in the general population, HSCR has long been regarded as a sex-modified multifactorial disorder',
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/8896569',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 858,
  'offsetInEndSection': 1012,
  'text': 'The inheritance of Hirschsprung disease is generally consistent with sex-modified multifactorial inheritance with a lower threshold of expression in males',
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/6650562',
  'endSection': 'abstract'},
 {'offsetInBeginSection': 820,
  'offsetInEndSection': 992,
  'text': "The non-Mendelian inheritance of sporadic non-syndromic Hirschsprung's disease proved to be complex; involvement of multiple loci was demonstrated in a multiplicative model",
  'beginSection': 'abstract',
  'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15617541',
  'endSection': 'abstract'}]

In [ ]:
data = pd.DataFrame(df['snippets'][0], columns=['offsetInBeginSection','offsetInEndSection','text','document','beginSection'])
# get document column last number till "/"
data['document'] = data['document'].astype(str).str.split('/').str[-1]
data = pd.concat([data,  pd.DataFrame(df.iloc[0]).T], axis = 1)
data['question'] = data['question'].fillna(str(df['question'][0]))
data['ideal_answer'] = data['ideal_answer'].fillna(str(df['ideal_answer'][0]))
data = data.drop(columns=['snippets','documents'])

In [ ]:
data

,offsetInBeginSection,offsetInEndSection,text,document,beginSection,question,ideal_answer
0,131,358,Hirschsprung disease (HSCR) is a multifactoria...,15829955,abstract,Is Hirschsprung disease a mendelian or a multi...,"[Coding sequence mutations in RET, GDNF, EDNRB..."
1,554,992,"In this study, we review the identification of...",15617541,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
2,397,939,"Coding sequence mutations in e.g. RET, GDNF, E...",12239580,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
3,941,1279,For almost all of the identified HSCR genes in...,12239580,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
4,129,358,Hirschsprung disease (HSCR) is a multifactori...,15829955,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
5,851,1007,The inheritance of Hirschsprung disease is ge...,6650562,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
6,131,359,Hirschsprung disease (HSCR) is a multifactoria...,15829955,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
7,0,131,"Differential contributions of rare and common,...",20598273,title,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
8,0,210,BACKGROUND: RET is the major gene associated t...,21995290,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
9,151,376,In the etiology of Hirschsprung disease variou...,15858239,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
10,0,83,Chromosomal and related Mendelian syndromes as...,23001136,title,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
11,715,818,The majority of the identified genes are relat...,15617541,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
12,151,375,In the etiology of Hirschsprung disease variou...,15858239,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
13,417,615,On the basis of a skewed sex-ratio (M/F = 4/1)...,8896569,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
14,858,1012,The inheritance of Hirschsprung disease is gen...,6650562,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."
15,820,992,The non-Mendelian inheritance of sporadic non-...,15617541,abstract,Is Hirschsprung disease a mendelian or a multi...,"[""Coding sequence mutations in RET, GDNF, EDNR..."

In [ ]:
def transform_snippets_to_rows(train_df):
    """
    Chuyển đổi cột snippets thành nhiều hàng và nhân bản các cột khác

    Parameters:
    -----------
    train_df : DataFrame
        DataFrame gốc có cột snippets cần được chuyển đổi

    Returns:
    --------
    DataFrame
        DataFrame đã được chuyển đổi với mỗi snippet thành một hàng riêng
    """

    # Khởi tạo list để lưu các DataFrame con
    transformed_dfs = []

    # Xử lý từng hàng trong train_df
    for idx in range(len(train_df)):
        # Tạo DataFrame từ snippets của hàng hiện tại
        snippet_df = pd.DataFrame(
            train_df['snippets'].iloc[idx],
            columns=['offsetInBeginSection', 'offsetInEndSection', 'text', 'document', 'beginSection']
        )

        # Xử lý cột document
        snippet_df['document'] = snippet_df['document'].astype(str).str.split('/').str[-1]

        # Thêm các cột khác từ hàng gốc
        other_cols = pd.DataFrame(train_df.iloc[idx]).T
        snippet_df = pd.concat([snippet_df, other_cols], axis=1)

        # Điền tất cả giá trị NaN bằng giá trị từ hàng đầu tiên của snippet_df
        # Check if the value is a list before filling NaNs
        for column in snippet_df.columns:
            # Exclude the text
            if column == 'text' or column == 'offsetInBeginSection' or column == 'offsetInEndSection':
                continue
            if snippet_df[column].isnull().any():
                fill_value = snippet_df[column].iloc[0]
                # If the fill value is a list, use an empty list instead
                if isinstance(fill_value, list):
                    fill_value = [] if fill_value == float('nan') else fill_value[0] # Handle NaN in fill_value
                snippet_df[column] = snippet_df[column].fillna(fill_value)
        # Điền các giá trị cho question và ideal_answer
        snippet_df['question'] = snippet_df['question'].fillna(str(train_df['question'].iloc[idx]))
        snippet_df['ideal_answer'] = snippet_df['ideal_answer'].fillna(str(train_df['ideal_answer'].iloc[idx]))
        # Loại bỏ các hàng có cả 3 giá trị null
        null_mask = snippet_df[['offsetInBeginSection', 'offsetInEndSection', 'text']].isnull().all(axis=1)
        snippet_df = snippet_df[~null_mask]
        # Thêm vào list các DataFrame đã xử lý
        transformed_dfs.append(snippet_df)

    # Ghép tất cả các DataFrame con
    result_df = pd.concat(transformed_dfs, axis=0, ignore_index=True)

    # Loại bỏ các cột không cần thiết
    result_df = result_df.drop(columns=['snippets', 'documents'])

    return result_df

In [ ]:
# Chuyển đổi toàn bộ DataFrame
transformed_df = transform_snippets_to_rows(df)
transformed_df

,offsetInBeginSection,offsetInEndSection,text,document,beginSection,question,ideal_answer
0,131.0,358.0,Hirschsprung disease (HSCR) is a multifactoria...,15829955,abstract,Is Hirschsprung disease a mendelian or a multi...,"[Coding sequence mutations in RET, GDNF, EDNRB..."
1,554.0,992.0,"In this study, we review the identification of...",15617541,abstract,Is Hirschsprung disease a mendelian or a multi...,"Coding sequence mutations in RET, GDNF, EDNRB,..."
2,397.0,939.0,"Coding sequence mutations in e.g. RET, GDNF, E...",12239580,abstract,Is Hirschsprung disease a mendelian or a multi...,"Coding sequence mutations in RET, GDNF, EDNRB,..."
3,941.0,1279.0,For almost all of the identified HSCR genes in...,12239580,abstract,Is Hirschsprung disease a mendelian or a multi...,"Coding sequence mutations in RET, GDNF, EDNRB,..."
4,129.0,358.0,Hirschsprung disease (HSCR) is a multifactori...,15829955,abstract,Is Hirschsprung disease a mendelian or a multi...,"Coding sequence mutations in RET, GDNF, EDNRB,..."
...,...,...,...,...,...,...,...
60151,0.0,78.0,Glofitamab Treatment in Relapsed or Refractory...,35626120,title,What disease can be treated with Glofitamab?,['Glofitamab is being tested for treatment of ...
60152,361.0,624.0,"In this study, we evaluated the safety and eff...",35626120,abstract,What disease can be treated with Glofitamab?,['Glofitamab is being tested for treatment of ...
60153,1106.0,1284.0,Our data suggest that glofitamab treatment is ...,35626120,abstract,What disease can be treated with Glofitamab?,['Glofitamab is being tested for treatment of ...
60154,674.0,976.0,"Bispecific antibodies such as epcoritamab, mos...",36198538,abstract,What disease can be treated with Glofitamab?,['Glofitamab is being tested for treatment of ...
60155,0.0,200.0,"Glofitamab, a novel CD20xCD3, T-cell-engaging ...",34941996,abstract,What disease can be treated with Glofitamab?,['Glofitamab is being tested for treatment of ...

In [ ]:
# Check if exist Nan valuea
transformed_df.isnull().sum()

offsetInBeginSection    0
offsetInEndSection      0
text                    0
document                0
beginSection            0
question                0
ideal_answer            0
dtype: int64

In [ ]:
# Check if text is duplicated
transformed_df.duplicated(subset=['text']).sum()

2697

In [ ]:
# Change from list in "idea_answer" to string
transformed_df['ideal_answer'] = str(transformed_df['ideal_answer'])

In [ ]:
transformed_df.head(5)

,offsetInBeginSection,offsetInEndSection,text,document,beginSection,question,ideal_answer
0,131.0,358.0,Hirschsprung disease (HSCR) is a multifactoria...,15829955,abstract,Is Hirschsprung disease a mendelian or a multi...,"0 [Coding sequence mutations in RET, GD..."
1,554.0,992.0,"In this study, we review the identification of...",15617541,abstract,Is Hirschsprung disease a mendelian or a multi...,"0 [Coding sequence mutations in RET, GD..."
2,397.0,939.0,"Coding sequence mutations in e.g. RET, GDNF, E...",12239580,abstract,Is Hirschsprung disease a mendelian or a multi...,"0 [Coding sequence mutations in RET, GD..."
3,941.0,1279.0,For almost all of the identified HSCR genes in...,12239580,abstract,Is Hirschsprung disease a mendelian or a multi...,"0 [Coding sequence mutations in RET, GD..."
4,129.0,358.0,Hirschsprung disease (HSCR) is a multifactori...,15829955,abstract,Is Hirschsprung disease a mendelian or a multi...,"0 [Coding sequence mutations in RET, GD..."

# Vector Search

In [ ]:
data = client.collections.get("MedicalArticles")

In [ ]:
response = data.aggregate.over_all(total_count=True)

print(response.total_count)
print(response.properties)

941723
{}

In [ ]:
# Define a function to call the endpoint and obtain embeddings
def vectorize(texts: List[str]) -> List[List[float]]:

    # 1. Load a pretrained Sentence Transformer model
    model = SentenceTransformer("all-MiniLM-L6-v2")
    embeddings = model.encode(texts)

    return embeddings

In [ ]:
query_text = "Lumbar Spine Degenerative?"
query_vector = vectorize([query_text])[0]

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
from transformers import pipeline

generator = pipeline(model="HuggingFaceH4/zephyr-7b-beta")
# Zephyr-beta is a conversational model, so let's pass it a chat instead of a single string
hyde = generator([{"role": "user", "content": "What is Lumber Spine Degeneration?"}], do_sample=False, max_new_tokens = 200)

config.json:   0%|          | 0.00/638 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/8 [00:00<?, ?it/s]

model-00001-of-00008.safetensors:   0%|          | 0.00/1.89G [00:00<?, ?B/s]

model-00002-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00003-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00004-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00005-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00006-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00007-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00008-of-00008.safetensors:   0%|          | 0.00/816M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.43k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/168 [00:00<?, ?B/s]

Device set to use cuda:0

In [ ]:
# put set of question into generator content

In [ ]:
generated_text = hyde[0]['generated_text']
print(generated_text[1]['content'])
ref_vector = vectorize([generated_text[1]['content']])[0]
print(ref_vector)

Lumber spine degeneration, also known as lumbar osteoarthritis, is a condition that occurs when the intervertebral discs and joints in the lower back (lumbar spine) begin to wear down over time. This degeneration can lead to pain, stiffness, and reduced mobility in the affected area. As the discs lose their cushioning ability, the bones (vertebrae) may begin to rub against each other, causing further discomfort and inflammation. Lumbar spine degeneration is a common condition in older adults, but it can also affect younger people who have experienced trauma or repetitive strain on the back. Treatment options may include physical therapy, medication, injections, or surgery in severe cases.
-0.017072327

In [ ]:
# Perform query
from weaviate.classes.query import HybridFusion
ref_response = data.query.hybrid(
    query=generated_text[1]['content'],
    fusion_type=HybridFusion.RELATIVE_SCORE,
    # limit=3,
    vector=query_vector,
    return_metadata=wq.MetadataQuery(distance=True),
)
# ref_response = data.query.near_vector(
#     near_vector=ref_vector,
#     limit=2,
#     return_metadata=wvc.query.MetadataQuery(certainty=True)
# )
for o in ref_response.objects:
    print(o.properties)
    print(o.metadata.distance)

{'pmid': '34087886', 'year': '2021', 'title': 'The new imaging findings: "Passing spine" without kissing.', 'meshMajor': ['Adult', 'Aged', 'Aged, 80 and over', 'Case-Control Studies', 'Female', 'Humans', 'Intervertebral Disc', 'Intervertebral Disc Degeneration', 'Lordosis', 'Lower Extremity', 'Lumbar Vertebrae', 'Lumbosacral Region', 'Male', 'Middle Aged', 'Somatoform Disorders', 'Spondylolisthesis', 'Tomography, X-Ray Computed', 'Vertebral Body'], 'abstractText': 'ABSTRACT: Case-control studies by examining the lumbar spine computed tomography (CT) findings focusing on the spinous processes."Passing spine" was defined as a lumbar degenerative change observed on CT images. In contrast, kissing spine, which is also an image finding, has been acknowledged as an established clinical condition. Therefore, we compared the passing spine group and the kissing spine group to investigate whether the 2 groups belong to a similar disease group; this would help explain the clinical and imaging characteristics of patients with passing spine.Previous studies have described the gradual increase in the height and thickness of the lumbar vertebral spinous processes that can occur in individuals aged >40\u200ayears, and reported that this progressive degeneration can lead to a condition termed "kissing spine."We examined the CT imaging of 373 patients with lumbar spinal disease and divided patients into 2 groups, the kissing spine (K) group and the passing spine (P) group, and compared the clinical (age, sex, presence/absence of lower extremity pain) and imaging data (localization of kissing or passing spine, intervertebral disc height at the level of kissing or passing spine, lumbar lordosis (LL) angle, presence/absence of vacuum phenomenon (VP) in the intervertebral discs and spondylolisthesis at the level of kissing or passing spine between the 2 groups.Compared with patients with kissing spine, patients with passing spine had an increased incidence of lower extremity pain, lower intervertebral disc height at the level of passing spine, relatively static LL, and VP commonly observed in the intervertebral discs at the level of passing spine.Because the clinical and imaging characteristics of patients with passing spine are different from those of patients with kissing spine, passing spine might be a pathological condition distinct from kissing spine.', 'journal': 'Medicine'}
None
{'pmid': '33548532', 'year': '2021', 'title': 'Single-Position Prone Transpsoas Lateral Interbody Fusion Including L4L5: Early Postoperative Outcomes.', 'meshMajor': ['Adult', 'Aged', 'Aged, 80 and over', 'Female', 'Humans', 'Intervertebral Disc', 'Lumbar Vertebrae', 'Lumbosacral Region', 'Male', 'Middle Aged', 'Patient Positioning', 'Postoperative Complications', 'Psoas Muscles', 'Spinal Fusion'], 'abstractText': 'BACKGROUND: The lateral lumbar interbody fusion (LLIF) was a revolutionary approach devised by Luiz Pimenta that allowed the surgeon to access the lumbar spine through the major psoas muscle. Although the traditional LLIF had enabled enormous advances, the technique has its drawbacks. A new concept to perform the traditional LLIF has been proposed, with the patient being prone to decubitus with slightly extended legs. Our study aims to analyze the early outcomes of patients who had undergone the prone transpsoas (PTP) for degenerative spine pathologies including the L4/5 level.METHODS: This study was multicentric, retrospective, nonrandomized, noncomparative, and observational. Only participants who received PTP in L4/5, with no more than 3 levels of intersomatics and fixation no further than S1, were included. The primary outcomes were the onset of new neurologic deficits and postoperative complications. Also, surgery details, such as blood loss and surgery duration, were measured. Neurologic deficits were accessed at the postoperative visit, which ranged from 7 to 14 days after surgery.RESULTS: Twenty-seven patients fulfilled the inclusion and exclusion criteria, with the majority receiving PTP only in L4/5 (66.6%). The mean surgery time was 182, with 29 minutes of mean transpsoas time. Of the patients, only 1 presented the onset of a motor deficit, while 3 patients presented a new sensory deficit. Five complications occurred, none intraoperative and 5 postoperative, with only 1 directly correlated with the access.CONCLUSIONS: The prone transpsoas is safe and feasible for approaching the L4/5 disk, presenting with a low rate of complication and new-onset neurologic deficits.', 'journal': 'World neurosurgery'}
None
{'pmid': '32032069', 'year': '2019', 'title': 'Avoiding and Managing Complications in Routine Lumbar Spine Surgery.', 'meshMajor': ['Elective Surgical Procedures', 'Humans', 'Lumbar Vertebrae', 'Postoperative Complications', 'Quality of Life', 'Registries', 'Spinal Fusion', 'Treatment Outcome'], 'journal': 'Instructional course lectures', 'abstractText': 'Elective lumbar surgery for common degenerative lumbar spine pathology has been consistently demonstrated to have excellent outcomes by multiple validated measures and improves patient quality of life. The rate of complication is low but not unavoidable; there is an increasing recognition of risk factors that can be mitigated to decrease complication rates. When complications occur, prompt recognition and management may minimize deleterious effects on patient outcome. There are considerations for identifying risk factors and, when possible, minimizing them and general strategies for identifying and managing common complications in lumbar spine surgery.'}
None
{'pmid': '32442808', 'title': 'Use of regenerative treatments in treatment of lumbar Degenerative Disc Disease: A systematic review.', 'year': '2020', 'meshMajor': ['Humans', 'Intervertebral Disc Degeneration', 'Low Back Pain', 'Lumbar Vertebrae', 'Regenerative Medicine', 'Stem Cell Transplantation', 'Total Disc Replacement'], 'abstractText': "Low back pain due to lumbar Degenerative Disc Disease (DDD) is one of the most common causes of disability and morbidity, particularly among older adults. Current research efforts in lumbar DDD management are shifting towards identifying and correcting the pathology in intervertebral discs without any external manipulation. Herein, we present a systematic review of current literature regarding regenerative treatments for lumbar DDD. An electronic search of databases including PubMed, Ovid/MEDLINE, Cochrane and Scopus was conducted for articles in all available years. Studies that investigated treatment for discogenic pain in lumbar DDD, including any type of stem cell or bone marrow concentrate as the treatment agent and studies that report both baseline and follow-up pain and Oswestry Disability Index (ODI) scores were included in the review. Changes in pain and ODI scores were calculated for 3-month, 6-month and 12-month periods. Six studies with a total of 93 patients were evaluated. Mean (SD) age of the pooled sample was 40.0(8.1) and 39.5% (32/81) of patients were female. Pain improvement was reported in 38.8% of patients at 3-month, 40.8% at 6-month and 44.1% at 12-month follow-up. Average improvement in ODI score for 3-month, 6-month and 12-month follow-ups was calculated to be 24.0, 26.5 and 25.7, respectively. Regenerative treatments are being increasingly employed across all spectrums of medicine. Review of six single arm studies revealed a potential positive impact in the preliminary results. However, these promising 'preliminary' results should not be interpreted as the definite treatment and should be validated with further prospective studies.", 'journal': 'Clinical neurology and neurosurgery'}
None
{'pmid': '32187081', 'title': 'Degenerative Spondylolisthesis: When to Fuse and When Not to? A New Scoring System.', 'year': '2020', 'meshMajor': ['Adult', 'Aged', 'Aged, 80 and over', 'Cohort Studies', 'Decision Making', 'Female', 'Humans', 'Lumbar Vertebrae', 'Male', 'Middle Aged', 'Minimally Invasive Surgical Procedures', 'Prospective Studies', 'Retrospective Studies', 'Sensitivity and Specificity', 'Severity of Illness Index', 'Spinal Fusion', 'Spondylolisthesis'], 'abstractText': 'STUDY DESIGN: A prospective cohort.OBJECTIVE: The objective of this study was to develop a scoring system for lumbar degenerative spondylolisthesis (LDS) that would guide decision-making.BACKGROUND: The management protocol for LDS has been under debate, with no guidelines. Most studies oversimplify LDS as a homogenous entity.MATERIALS AND METHODS: A retrospective analysis of 131 patients who underwent surgery for LDS between July 2007 and October 2011 with a minimum follow-up of 3 years was carried out on the basis of clinical, radiologic, and technical factors. A scoring system was conceptualized. Clinical: back pain score-2, age younger than 70 years-1, high-demand activity-1. Radiologic: segmental kyphosis-1.5, segmental dynamic translation-1, disk height >50% of adjacent level-1, facet effusion-1, sagittal facet-orientation-1. Technical: feasibility to decompress without causing instability-1.5. Its reliability was ascertained by a univariate analysis. The benchmark was set at 5.5 according to the Youden Index. This was followed by a prospective study for reliability analysis between November 2011 and January 2017 of 52 patients who underwent stand-alone decompression in LDS with a minimum follow-up of 24 months. Outcomes were evaluated using the Oswestry Disability Index and the Visual Analog Scale. Interobserver variability was determined. None of the patients in the retrospective or prospective group had undergone any lumbar surgery previously.RESULTS: The mean Oswestry Disability Index and Visual Analog Scale of both the groups in the retrospective and the stand-alone decompression groups in prospective studies showed significant improvement. The interobserver reliability was high, with a ê value of 0.847.CONCLUSIONS: The proposed scoring system helps view LDS as a heterogenous condition and assists in tailoring treatment for individual patients. For a select subgroup of patients with LDS, minimally invasive decompression (unilateral laminotomy and bilateral decompression using a minimally invasive surgery tubular retractor system) without fusion is adequate.LEVEL OF EVIDENCE: Level III.', 'journal': 'Clinical spine surgery'}
None
{'pmid': '32214300', 'year': '2020', 'title': 'Percutaneous Transforaminal Endoscopic Lumbar Interbody Fusion for Degenerative Lumbar Diseases: A Consecutive Case Series with Mean 2-Year Follow-Up.', 'meshMajor': ['Adult', 'Aged', 'Endoscopy', 'Female', 'Follow-Up Studies', 'Humans', 'Intervertebral Disc Degeneration', 'Intervertebral Disc Displacement', 'Lumbar Vertebrae', 'Male', 'Middle Aged', 'Retrospective Studies', 'Spinal Fusion', 'Spondylolisthesis', 'Treatment Outcome'], 'journal': 'Pain physician', 'abstractText': 'BACKGROUND: Conventional open surgical procedures may cause massive dissections of the spine, higher perioperative complications, prolonged hospitalization, protracted rehabilitation programs and recovery. Percutaneous endoscopic lumbar interbody fusion (PELIF) is an evolving treatment option.OBJECTIVES: To present the detailed procedure and preliminary clinical and radiologic results of PELIF for degenerative lumbar diseases.STUDY DESIGN: A retrospective cohort study.SETTING: A university affiliated tertiary hospital.METHODS: The medical records of patients with degenerative lumbar diseases who underwent PELIF between January 2016 and December 2017 were retrospectively reviewed. Surgical level, surgical time, blood loss, hospital length of stay, and perioperative complications were discussed. Patients were also evaluated for pain by the Visual Analog Scale (VAS), and functional assessment by the Oswestry Disability Index (ODI) and the 36-Item Short Form Health Survey (SF-36), including Physical Component Summary (PCS) and Mental Component Summary (MCS) preoperatively, postoperatively, and during the follow-up period.RESULTS: Thirty-nine consecutive patients (25 men and 14 women) with a mean age of 59.0 years (range, 39-77 years) were enrolled. The average surgical time was 213.8 ± 31.7 minutes (range, 185-324 minutes). Mean estimated blood loss was 25.0 ± 12.6 mL (range, 15-50 mL). At the latest follow-up visit, the VAS scores for back pain, leg pain, ODI, and SF-36 (MCS/PCS) scores improved 89.5%, 95.0%, 71.2%, and 37.5%/58%, respectively. Reoperations were performed in one patient for residual disc mass and one for misplacement of pedicle screw. Fusion was achieved in all patients.LIMITATIONS: The presented results are preliminary and should be interpreted taking the limitations into account, including nonrandomized design, relatively small sample size, and less intensive follow-up period.CONCLUSIONS: The presented PELIF technique seems to be a promising surgical alternative for the treatment of patients with specific degenerative lumbar diseases. Randomized studies with larger sample size and long-term follow-up duration are needed to validate the superiorities of this versatile surgery.KEY WORDS: Endoscopic, minimally invasive spine surgery, lumbar interbody fusion, disc herniation, spondylolisthesis.'}
None
{'pmid': '33157913', 'title': 'The effect of preoperative degenerative spondylolisthesis on postoperative outcomes of degenerative lumbar spinal stenosis: A single-center cohort study protocol.', 'year': '2020', 'meshMajor': ['Aged', 'Disability Evaluation', 'Female', 'Humans', 'Laminectomy', 'Lumbar Vertebrae', 'Magnetic Resonance Imaging', 'Male', 'Postoperative Complications', 'Reoperation', 'Research Design', 'Retrospective Studies', 'Spinal Stenosis', 'Spondylolisthesis', 'Visual Analog Scale'], 'abstractText': 'BACKGROUND: Most degenerative lumbar spinal stenosis (DLSS) patients primitively received the conservative treatment to control symptoms. In order to develop an optimal surgical treatment strategy, it is very significant to understand how the degenerative lumbar spondylolisthesis (DS) affects the effect of decompression in the DLSS. Thus, the aim of this current study was to explore whether the concomitant DS would affect the effect of decompression alone in the patients with DLSS.METHODS: The current study was carried out at our hospital and it was approved through our institutional review committee of General Hospital of Ningxia Medical University. During the period from January 2015 to December 2017, in our study, we identified consecutive patients who received the minimally invasive laminectomy to treat the DLSS. The inclusion criterion included radicular leg pain or neurogenic claudication with the neurological symptoms associated with DLSS syndrome, magnetic resonance imaging of the lumbar spine reveals at least 1 level of serious stenosis, the conservative treatment failed for at least 3 months, and patients agreed to provide the postoperative details. The major outcomes of this present research was Oswestry Disability Index. Secondary outcomes of this current study involved visual analog score, short form-36, surgical revision rate as well as complications.RESULTS: We assumed that previous DS possessed a negative effect on the postoperative results of the DLSS patients.TRIAL REGISTRATION: researchregistry5943.', 'journal': 'Medicine'}
None
{'pmid': '31253158', 'title': 'Topping-off surgery vs posterior lumbar interbody fusion for degenerative lumbar disease: a comparative study of clinical efficacy and adjacent segment degeneration.', 'year': '2019', 'meshMajor': ['Aged', 'Female', 'Follow-Up Studies', 'Humans', 'Internal Fixators', 'Intervertebral Disc Degeneration', 'Lumbar Vertebrae', 'Male', 'Middle Aged', 'Retrospective Studies', 'Spinal Fusion', 'Treatment Outcome'], 'abstractText': 'BACKGROUND: Studies have shown that adjacent segment degeneration (ASD) is a common complication after posterior lumbar interbody fusion (PLIF), even a second surgery is required for some patients. It remains unclear whether the non-fusion surgery can relieve ASD. Therefore, this study aims to investigate the clinical outcomes of Topping-off surgery (fusion combined with Coflex) and PLIF for degenerative lumbar disease (DLD) and the efficacy on preventing ASD.METHOD: A retrospective analysis was performed on the clinical data of 99 patients with DLD from January 2011 to December 2014, who were performed by Topping-off surgery (L4-5 PLIF + L3-4 Coflex, n\u2009=\u200945) or PLIF (L3-5 PLIF, n\u2009=\u200954). All patients included in the analysis had a minimum of 3\xa0years of follow-up. Clinical data were used to assess the clinical efficacy, and radiographic parameters were measured for evaluation of the incidence of ASD.RESULTS: The mean ages of Topping-off group and PLIF group were 53.5 and 65.7\u2009years old, respectively (P\xa0<\u20090.05). The surgical time, intraoperative blood loss, Oswestry disability index (ODI), and visual analog scale (VAS) were significantly different between the two groups (P\xa0<\u20090.05). Intervertebral mobility (L2-L3) of the Topping-off group was not changed significantly at 3\xa0years after surgery than before (P\u2009>\u20090.05), while that of PLIF group was increased considerably (P\u2009<\u20090.05). As to intergroup comparison, intervertebral mobility (L2-L3) of Topping-off group was superior to those of the PLIF group (P\u2009<\u20090.05). Surprisingly, there was no significant difference in the general adjacent segment mobility (GASM) at L2-4 of the Topping-off group and intervertebral mobility (L2-L3) of PLIF group at 3\xa0years after surgery (P\u2009>\u20090.05). Lumbar MRI at three post-operative years indicated that the modified Pfirrman grading of disc (L2-L3) in the Topping-off group was much better than that of the PLIF group (P\u2009<\u20090.05).CONCLUSION: This study showed that Topping-off surgery had the benefits of less invasiveness, less bleeding, and comparable clinical efficacy as PLIF for DLD. The segment with Coflex insertion undertook part of the mobility and stress in the proximal lumbar spine, which is conducive to alleviating ASD.', 'journal': 'Journal of orthopaedic surgery and research'}
None

In [ ]:
from weaviate.classes.query import HybridFusion
# response = data.query.hybrid(
#     query=query_text,
#     fusion_type=HybridFusion.RELATIVE_SCORE,
#     limit=3,
#     vector=query_vector,
#     return_metadata=wq.MetadataQuery(distance=True),
# )
response = data.query.near_vector(
    near_vector=query_vector,
    # limit=2,
    return_metadata=wvc.query.MetadataQuery(certainty=True)
)
for o in response.objects:
    print(o.properties)
    print(o.metadata.distance)

{'pmid': '33548532', 'title': 'Single-Position Prone Transpsoas Lateral Interbody Fusion Including L4L5: Early Postoperative Outcomes.', 'year': '2021', 'meshMajor': ['Adult', 'Aged', 'Aged, 80 and over', 'Female', 'Humans', 'Intervertebral Disc', 'Lumbar Vertebrae', 'Lumbosacral Region', 'Male', 'Middle Aged', 'Patient Positioning', 'Postoperative Complications', 'Psoas Muscles', 'Spinal Fusion'], 'abstractText': 'BACKGROUND: The lateral lumbar interbody fusion (LLIF) was a revolutionary approach devised by Luiz Pimenta that allowed the surgeon to access the lumbar spine through the major psoas muscle. Although the traditional LLIF had enabled enormous advances, the technique has its drawbacks. A new concept to perform the traditional LLIF has been proposed, with the patient being prone to decubitus with slightly extended legs. Our study aims to analyze the early outcomes of patients who had undergone the prone transpsoas (PTP) for degenerative spine pathologies including the L4/5 level.METHODS: This study was multicentric, retrospective, nonrandomized, noncomparative, and observational. Only participants who received PTP in L4/5, with no more than 3 levels of intersomatics and fixation no further than S1, were included. The primary outcomes were the onset of new neurologic deficits and postoperative complications. Also, surgery details, such as blood loss and surgery duration, were measured. Neurologic deficits were accessed at the postoperative visit, which ranged from 7 to 14 days after surgery.RESULTS: Twenty-seven patients fulfilled the inclusion and exclusion criteria, with the majority receiving PTP only in L4/5 (66.6%). The mean surgery time was 182, with 29 minutes of mean transpsoas time. Of the patients, only 1 presented the onset of a motor deficit, while 3 patients presented a new sensory deficit. Five complications occurred, none intraoperative and 5 postoperative, with only 1 directly correlated with the access.CONCLUSIONS: The prone transpsoas is safe and feasible for approaching the L4/5 disk, presenting with a low rate of complication and new-onset neurologic deficits.', 'journal': 'World neurosurgery'}
None
{'pmid': '34087886', 'year': '2021', 'title': 'The new imaging findings: "Passing spine" without kissing.', 'meshMajor': ['Adult', 'Aged', 'Aged, 80 and over', 'Case-Control Studies', 'Female', 'Humans', 'Intervertebral Disc', 'Intervertebral Disc Degeneration', 'Lordosis', 'Lower Extremity', 'Lumbar Vertebrae', 'Lumbosacral Region', 'Male', 'Middle Aged', 'Somatoform Disorders', 'Spondylolisthesis', 'Tomography, X-Ray Computed', 'Vertebral Body'], 'abstractText': 'ABSTRACT: Case-control studies by examining the lumbar spine computed tomography (CT) findings focusing on the spinous processes."Passing spine" was defined as a lumbar degenerative change observed on CT images. In contrast, kissing spine, which is also an image finding, has been acknowledged as an established clinical condition. Therefore, we compared the passing spine group and the kissing spine group to investigate whether the 2 groups belong to a similar disease group; this would help explain the clinical and imaging characteristics of patients with passing spine.Previous studies have described the gradual increase in the height and thickness of the lumbar vertebral spinous processes that can occur in individuals aged >40\u200ayears, and reported that this progressive degeneration can lead to a condition termed "kissing spine."We examined the CT imaging of 373 patients with lumbar spinal disease and divided patients into 2 groups, the kissing spine (K) group and the passing spine (P) group, and compared the clinical (age, sex, presence/absence of lower extremity pain) and imaging data (localization of kissing or passing spine, intervertebral disc height at the level of kissing or passing spine, lumbar lordosis (LL) angle, presence/absence of vacuum phenomenon (VP) in the intervertebral discs and spondylolisthesis at the level of kissing or passing spine between the 2 groups.Compared with patients with kissing spine, patients with passing spine had an increased incidence of lower extremity pain, lower intervertebral disc height at the level of passing spine, relatively static LL, and VP commonly observed in the intervertebral discs at the level of passing spine.Because the clinical and imaging characteristics of patients with passing spine are different from those of patients with kissing spine, passing spine might be a pathological condition distinct from kissing spine.', 'journal': 'Medicine'}
None
{'pmid': '32032069', 'title': 'Avoiding and Managing Complications in Routine Lumbar Spine Surgery.', 'year': '2019', 'meshMajor': ['Elective Surgical Procedures', 'Humans', 'Lumbar Vertebrae', 'Postoperative Complications', 'Quality of Life', 'Registries', 'Spinal Fusion', 'Treatment Outcome'], 'abstractText': 'Elective lumbar surgery for common degenerative lumbar spine pathology has been consistently demonstrated to have excellent outcomes by multiple validated measures and improves patient quality of life. The rate of complication is low but not unavoidable; there is an increasing recognition of risk factors that can be mitigated to decrease complication rates. When complications occur, prompt recognition and management may minimize deleterious effects on patient outcome. There are considerations for identifying risk factors and, when possible, minimizing them and general strategies for identifying and managing common complications in lumbar spine surgery.', 'journal': 'Instructional course lectures'}
None
{'pmid': '32442808', 'year': '2020', 'title': 'Use of regenerative treatments in treatment of lumbar Degenerative Disc Disease: A systematic review.', 'meshMajor': ['Humans', 'Intervertebral Disc Degeneration', 'Low Back Pain', 'Lumbar Vertebrae', 'Regenerative Medicine', 'Stem Cell Transplantation', 'Total Disc Replacement'], 'abstractText': "Low back pain due to lumbar Degenerative Disc Disease (DDD) is one of the most common causes of disability and morbidity, particularly among older adults. Current research efforts in lumbar DDD management are shifting towards identifying and correcting the pathology in intervertebral discs without any external manipulation. Herein, we present a systematic review of current literature regarding regenerative treatments for lumbar DDD. An electronic search of databases including PubMed, Ovid/MEDLINE, Cochrane and Scopus was conducted for articles in all available years. Studies that investigated treatment for discogenic pain in lumbar DDD, including any type of stem cell or bone marrow concentrate as the treatment agent and studies that report both baseline and follow-up pain and Oswestry Disability Index (ODI) scores were included in the review. Changes in pain and ODI scores were calculated for 3-month, 6-month and 12-month periods. Six studies with a total of 93 patients were evaluated. Mean (SD) age of the pooled sample was 40.0(8.1) and 39.5% (32/81) of patients were female. Pain improvement was reported in 38.8% of patients at 3-month, 40.8% at 6-month and 44.1% at 12-month follow-up. Average improvement in ODI score for 3-month, 6-month and 12-month follow-ups was calculated to be 24.0, 26.5 and 25.7, respectively. Regenerative treatments are being increasingly employed across all spectrums of medicine. Review of six single arm studies revealed a potential positive impact in the preliminary results. However, these promising 'preliminary' results should not be interpreted as the definite treatment and should be validated with further prospective studies.", 'journal': 'Clinical neurology and neurosurgery'}
None
{'pmid': '32187081', 'year': '2020', 'title': 'Degenerative Spondylolisthesis: When to Fuse and When Not to? A New Scoring System.', 'meshMajor': ['Adult', 'Aged', 'Aged, 80 and over', 'Cohort Studies', 'Decision Making', 'Female', 'Humans', 'Lumbar Vertebrae', 'Male', 'Middle Aged', 'Minimally Invasive Surgical Procedures', 'Prospective Studies', 'Retrospective Studies', 'Sensitivity and Specificity', 'Severity of Illness Index', 'Spinal Fusion', 'Spondylolisthesis'], 'abstractText': 'STUDY DESIGN: A prospective cohort.OBJECTIVE: The objective of this study was to develop a scoring system for lumbar degenerative spondylolisthesis (LDS) that would guide decision-making.BACKGROUND: The management protocol for LDS has been under debate, with no guidelines. Most studies oversimplify LDS as a homogenous entity.MATERIALS AND METHODS: A retrospective analysis of 131 patients who underwent surgery for LDS between July 2007 and October 2011 with a minimum follow-up of 3 years was carried out on the basis of clinical, radiologic, and technical factors. A scoring system was conceptualized. Clinical: back pain score-2, age younger than 70 years-1, high-demand activity-1. Radiologic: segmental kyphosis-1.5, segmental dynamic translation-1, disk height >50% of adjacent level-1, facet effusion-1, sagittal facet-orientation-1. Technical: feasibility to decompress without causing instability-1.5. Its reliability was ascertained by a univariate analysis. The benchmark was set at 5.5 according to the Youden Index. This was followed by a prospective study for reliability analysis between November 2011 and January 2017 of 52 patients who underwent stand-alone decompression in LDS with a minimum follow-up of 24 months. Outcomes were evaluated using the Oswestry Disability Index and the Visual Analog Scale. Interobserver variability was determined. None of the patients in the retrospective or prospective group had undergone any lumbar surgery previously.RESULTS: The mean Oswestry Disability Index and Visual Analog Scale of both the groups in the retrospective and the stand-alone decompression groups in prospective studies showed significant improvement. The interobserver reliability was high, with a ê value of 0.847.CONCLUSIONS: The proposed scoring system helps view LDS as a heterogenous condition and assists in tailoring treatment for individual patients. For a select subgroup of patients with LDS, minimally invasive decompression (unilateral laminotomy and bilateral decompression using a minimally invasive surgery tubular retractor system) without fusion is adequate.LEVEL OF EVIDENCE: Level III.', 'journal': 'Clinical spine surgery'}
None
{'pmid': '32214300', 'year': '2020', 'title': 'Percutaneous Transforaminal Endoscopic Lumbar Interbody Fusion for Degenerative Lumbar Diseases: A Consecutive Case Series with Mean 2-Year Follow-Up.', 'meshMajor': ['Adult', 'Aged', 'Endoscopy', 'Female', 'Follow-Up Studies', 'Humans', 'Intervertebral Disc Degeneration', 'Intervertebral Disc Displacement', 'Lumbar Vertebrae', 'Male', 'Middle Aged', 'Retrospective Studies', 'Spinal Fusion', 'Spondylolisthesis', 'Treatment Outcome'], 'journal': 'Pain physician', 'abstractText': 'BACKGROUND: Conventional open surgical procedures may cause massive dissections of the spine, higher perioperative complications, prolonged hospitalization, protracted rehabilitation programs and recovery. Percutaneous endoscopic lumbar interbody fusion (PELIF) is an evolving treatment option.OBJECTIVES: To present the detailed procedure and preliminary clinical and radiologic results of PELIF for degenerative lumbar diseases.STUDY DESIGN: A retrospective cohort study.SETTING: A university affiliated tertiary hospital.METHODS: The medical records of patients with degenerative lumbar diseases who underwent PELIF between January 2016 and December 2017 were retrospectively reviewed. Surgical level, surgical time, blood loss, hospital length of stay, and perioperative complications were discussed. Patients were also evaluated for pain by the Visual Analog Scale (VAS), and functional assessment by the Oswestry Disability Index (ODI) and the 36-Item Short Form Health Survey (SF-36), including Physical Component Summary (PCS) and Mental Component Summary (MCS) preoperatively, postoperatively, and during the follow-up period.RESULTS: Thirty-nine consecutive patients (25 men and 14 women) with a mean age of 59.0 years (range, 39-77 years) were enrolled. The average surgical time was 213.8 ± 31.7 minutes (range, 185-324 minutes). Mean estimated blood loss was 25.0 ± 12.6 mL (range, 15-50 mL). At the latest follow-up visit, the VAS scores for back pain, leg pain, ODI, and SF-36 (MCS/PCS) scores improved 89.5%, 95.0%, 71.2%, and 37.5%/58%, respectively. Reoperations were performed in one patient for residual disc mass and one for misplacement of pedicle screw. Fusion was achieved in all patients.LIMITATIONS: The presented results are preliminary and should be interpreted taking the limitations into account, including nonrandomized design, relatively small sample size, and less intensive follow-up period.CONCLUSIONS: The presented PELIF technique seems to be a promising surgical alternative for the treatment of patients with specific degenerative lumbar diseases. Randomized studies with larger sample size and long-term follow-up duration are needed to validate the superiorities of this versatile surgery.KEY WORDS: Endoscopic, minimally invasive spine surgery, lumbar interbody fusion, disc herniation, spondylolisthesis.'}
None
{'pmid': '33157913', 'title': 'The effect of preoperative degenerative spondylolisthesis on postoperative outcomes of degenerative lumbar spinal stenosis: A single-center cohort study protocol.', 'year': '2020', 'meshMajor': ['Aged', 'Disability Evaluation', 'Female', 'Humans', 'Laminectomy', 'Lumbar Vertebrae', 'Magnetic Resonance Imaging', 'Male', 'Postoperative Complications', 'Reoperation', 'Research Design', 'Retrospective Studies', 'Spinal Stenosis', 'Spondylolisthesis', 'Visual Analog Scale'], 'abstractText': 'BACKGROUND: Most degenerative lumbar spinal stenosis (DLSS) patients primitively received the conservative treatment to control symptoms. In order to develop an optimal surgical treatment strategy, it is very significant to understand how the degenerative lumbar spondylolisthesis (DS) affects the effect of decompression in the DLSS. Thus, the aim of this current study was to explore whether the concomitant DS would affect the effect of decompression alone in the patients with DLSS.METHODS: The current study was carried out at our hospital and it was approved through our institutional review committee of General Hospital of Ningxia Medical University. During the period from January 2015 to December 2017, in our study, we identified consecutive patients who received the minimally invasive laminectomy to treat the DLSS. The inclusion criterion included radicular leg pain or neurogenic claudication with the neurological symptoms associated with DLSS syndrome, magnetic resonance imaging of the lumbar spine reveals at least 1 level of serious stenosis, the conservative treatment failed for at least 3 months, and patients agreed to provide the postoperative details. The major outcomes of this present research was Oswestry Disability Index. Secondary outcomes of this current study involved visual analog score, short form-36, surgical revision rate as well as complications.RESULTS: We assumed that previous DS possessed a negative effect on the postoperative results of the DLSS patients.TRIAL REGISTRATION: researchregistry5943.', 'journal': 'Medicine'}
None
{'pmid': '31253158', 'year': '2019', 'title': 'Topping-off surgery vs posterior lumbar interbody fusion for degenerative lumbar disease: a comparative study of clinical efficacy and adjacent segment degeneration.', 'meshMajor': ['Aged', 'Female', 'Follow-Up Studies', 'Humans', 'Internal Fixators', 'Intervertebral Disc Degeneration', 'Lumbar Vertebrae', 'Male', 'Middle Aged', 'Retrospective Studies', 'Spinal Fusion', 'Treatment Outcome'], 'journal': 'Journal of orthopaedic surgery and research', 'abstractText': 'BACKGROUND: Studies have shown that adjacent segment degeneration (ASD) is a common complication after posterior lumbar interbody fusion (PLIF), even a second surgery is required for some patients. It remains unclear whether the non-fusion surgery can relieve ASD. Therefore, this study aims to investigate the clinical outcomes of Topping-off surgery (fusion combined with Coflex) and PLIF for degenerative lumbar disease (DLD) and the efficacy on preventing ASD.METHOD: A retrospective analysis was performed on the clinical data of 99 patients with DLD from January 2011 to December 2014, who were performed by Topping-off surgery (L4-5 PLIF + L3-4 Coflex, n\u2009=\u200945) or PLIF (L3-5 PLIF, n\u2009=\u200954). All patients included in the analysis had a minimum of 3\xa0years of follow-up. Clinical data were used to assess the clinical efficacy, and radiographic parameters were measured for evaluation of the incidence of ASD.RESULTS: The mean ages of Topping-off group and PLIF group were 53.5 and 65.7\u2009years old, respectively (P\xa0<\u20090.05). The surgical time, intraoperative blood loss, Oswestry disability index (ODI), and visual analog scale (VAS) were significantly different between the two groups (P\xa0<\u20090.05). Intervertebral mobility (L2-L3) of the Topping-off group was not changed significantly at 3\xa0years after surgery than before (P\u2009>\u20090.05), while that of PLIF group was increased considerably (P\u2009<\u20090.05). As to intergroup comparison, intervertebral mobility (L2-L3) of Topping-off group was superior to those of the PLIF group (P\u2009<\u20090.05). Surprisingly, there was no significant difference in the general adjacent segment mobility (GASM) at L2-4 of the Topping-off group and intervertebral mobility (L2-L3) of PLIF group at 3\xa0years after surgery (P\u2009>\u20090.05). Lumbar MRI at three post-operative years indicated that the modified Pfirrman grading of disc (L2-L3) in the Topping-off group was much better than that of the PLIF group (P\u2009<\u20090.05).CONCLUSION: This study showed that Topping-off surgery had the benefits of less invasiveness, less bleeding, and comparable clinical efficacy as PLIF for DLD. The segment with Coflex insertion undertook part of the mobility and stress in the proximal lumbar spine, which is conducive to alleviating ASD.'}
None

In [ ]:
!pip --quiet install llama-index
!pip --quiet install llama_index.llms.ollama
!pip --quiet install -U bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 28.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.1/247.1 kB 21.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 26.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 61.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.1/69.1 MB 15.0 MB/s eta 0:00:00

In [ ]:
#Import LLM model from Ollama (llama3.1:405B)
from llama_index.llms.ollama import Ollama
from llama_index.core import Settings
# llm = Ollama(model="llama3.1:405B", base_url="http://localhost:11434")

In [ ]:
# from llama_index.core import PromptTemplate

template = """Context information is below:
              ---------------------
              ${context_str}
              ---------------------
              Given the context information above I want you to think
              step by step to answer the query in a crisp manner,
              incase you don't know the answer say 'I don't know!'

              Query: {query_text}

              Answer:"""

# qa_prompt_tmpl = PromptTemplate(template)

In [ ]:
# Inspect the response
temp = []
for o in response.objects:
    print(
        o.properties["meshMajor"], o.properties["abstractText"]
    )
    temp.append(f"Context information is below: {o.properties['abstractText']} Given the context information above I want you to think step by step to answer the query in a crisp manner, incase you don't know the answer say 'I don't know!' Query: {query_text} Answer:")  # Print the title and release year (note the release date is a datetime object)
    print(
        # f"Distance to query: {o.metadata.distance:.3f}\n"
    )  # Print the distance of the object from the query

client.close()

['Adult', 'Aged', 'Aged, 80 and over', 'Case-Control Studies', 'Female', 'Humans', 'Intervertebral Disc', 'Intervertebral Disc Degeneration', 'Lordosis', 'Lower Extremity', 'Lumbar Vertebrae', 'Lumbosacral Region', 'Male', 'Middle Aged', 'Somatoform Disorders', 'Spondylolisthesis', 'Tomography, X-Ray Computed', 'Vertebral Body'] ABSTRACT: Case-control studies by examining the lumbar spine computed tomography (CT) findings focusing on the spinous processes."Passing spine" was defined as a lumbar degenerative change observed on CT images. In contrast, kissing spine, which is also an image finding, has been acknowledged as an established clinical condition. Therefore, we compared the passing spine group and the kissing spine group to investigate whether the 2 groups belong to a similar disease group; this would help explain the clinical and imaging characteristics of patients with passing spine.Previous studies have described the gradual increase in the height and thickness of the lumbar vertebral spinous processes that can occur in individuals aged >40 years, and reported that this progressive degeneration can lead to a condition termed "kissing spine."We examined the CT imaging of 373 patients with lumbar spinal disease and divided patients into 2 groups, the kissing spine (K) group and the passing spine (P) group, and compared the clinical (age, sex, presence/absence of lower extremity pain) and imaging data (localization of kissing or passing spine, intervertebral disc height at the level of kissing or passing spine, lumbar lordosis (LL) angle, presence/absence of vacuum phenomenon (VP) in the intervertebral discs and spondylolisthesis at the level of kissing or passing spine between the 2 groups.Compared with patients with kissing spine, patients with passing spine had an increased incidence of lower extremity pain, lower intervertebral disc height at the level of passing spine, relatively static LL, and VP commonly observed in the intervertebral discs at the level of passing spine.Because the clinical and imaging characteristics of patients with passing spine are different from those of patients with kissing spine, passing spine might be a pathological condition distinct from kissing spine.

['Adult', 'Aged', 'Aged, 80 and over', 'Female', 'Humans', 'Intervertebral Disc', 'Lumbar Vertebrae', 'Lumbosacral Region', 'Male', 'Middle Aged', 'Patient Positioning', 'Postoperative Complications', 'Psoas Muscles', 'Spinal Fusion'] BACKGROUND: The lateral lumbar interbody fusion (LLIF) was a revolutionary approach devised by Luiz Pimenta that allowed the surgeon to access the lumbar spine through the major psoas muscle. Although the traditional LLIF had enabled enormous advances, the technique has its drawbacks. A new concept to perform the traditional LLIF has been proposed, with the patient being prone to decubitus with slightly extended legs. Our study aims to analyze the early outcomes of patients who had undergone the prone transpsoas (PTP) for degenerative spine pathologies including the L4/5 level.METHODS: This study was multicentric, retrospective, nonrandomized, noncomparative, and observational. Only participants who received PTP in L4/5, with no more than 3 levels of intersomatics and fixation no further than S1, were included. The primary outcomes were the onset of new neurologic deficits and postoperative complications. Also, surgery details, such as blood loss and surgery duration, were measured. Neurologic deficits were accessed at the postoperative visit, which ranged from 7 to 14 days after surgery.RESULTS: Twenty-seven patients fulfilled the inclusion and exclusion criteria, with the majority receiving PTP only in L4/5 (66.6%). The mean surgery time was 182, with 29 minutes of mean transpsoas time. Of the patients, only 1 presented the onset of a motor deficit, while 3 patients presented a new sensory deficit. Five complications occurred, none intraoperative and 5 postoperative, with only 1 directly correlated with the access.CONCLUSIONS: The prone transpsoas is safe and feasible for approaching the L4/5 disk, presenting with a low rate of complication and new-onset neurologic deficits.

['Elective Surgical Procedures', 'Humans', 'Lumbar Vertebrae', 'Postoperative Complications', 'Quality of Life', 'Registries', 'Spinal Fusion', 'Treatment Outcome'] Elective lumbar surgery for common degenerative lumbar spine pathology has been consistently demonstrated to have excellent outcomes by multiple validated measures and improves patient quality of life. The rate of complication is low but not unavoidable; there is an increasing recognition of risk factors that can be mitigated to decrease complication rates. When complications occur, prompt recognition and management may minimize deleterious effects on patient outcome. There are considerations for identifying risk factors and, when possible, minimizing them and general strategies for identifying and managing common complications in lumbar spine surgery.

['Humans', 'Intervertebral Disc Degeneration', 'Low Back Pain', 'Lumbar Vertebrae', 'Regenerative Medicine', 'Stem Cell Transplantation', 'Total Disc Replacement'] Low back pain due to lumbar Degenerative Disc Disease (DDD) is one of the most common causes of disability and morbidity, particularly among older adults. Current research efforts in lumbar DDD management are shifting towards identifying and correcting the pathology in intervertebral discs without any external manipulation. Herein, we present a systematic review of current literature regarding regenerative treatments for lumbar DDD. An electronic search of databases including PubMed, Ovid/MEDLINE, Cochrane and Scopus was conducted for articles in all available years. Studies that investigated treatment for discogenic pain in lumbar DDD, including any type of stem cell or bone marrow concentrate as the treatment agent and studies that report both baseline and follow-up pain and Oswestry Disability Index (ODI) scores were included in the review. Changes in pain and ODI scores were calculated for 3-month, 6-month and 12-month periods. Six studies with a total of 93 patients were evaluated. Mean (SD) age of the pooled sample was 40.0(8.1) and 39.5% (32/81) of patients were female. Pain improvement was reported in 38.8% of patients at 3-month, 40.8% at 6-month and 44.1% at 12-month follow-up. Average improvement in ODI score for 3-month, 6-month and 12-month follow-ups was calculated to be 24.0, 26.5 and 25.7, respectively. Regenerative treatments are being increasingly employed across all spectrums of medicine. Review of six single arm studies revealed a potential positive impact in the preliminary results. However, these promising 'preliminary' results should not be interpreted as the definite treatment and should be validated with further prospective studies.

['Adult', 'Aged', 'Aged, 80 and over', 'Cohort Studies', 'Decision Making', 'Female', 'Humans', 'Lumbar Vertebrae', 'Male', 'Middle Aged', 'Minimally Invasive Surgical Procedures', 'Prospective Studies', 'Retrospective Studies', 'Sensitivity and Specificity', 'Severity of Illness Index', 'Spinal Fusion', 'Spondylolisthesis'] STUDY DESIGN: A prospective cohort.OBJECTIVE: The objective of this study was to develop a scoring system for lumbar degenerative spondylolisthesis (LDS) that would guide decision-making.BACKGROUND: The management protocol for LDS has been under debate, with no guidelines. Most studies oversimplify LDS as a homogenous entity.MATERIALS AND METHODS: A retrospective analysis of 131 patients who underwent surgery for LDS between July 2007 and October 2011 with a minimum follow-up of 3 years was carried out on the basis of clinical, radiologic, and technical factors. A scoring system was conceptualized. Clinical: back pain score-2, age younger than 70 years-1, high-demand activity-1. Radiologic: segmental kyphosis-1.5, segmental dynamic translation-1, disk height >50% of adjacent level-1, facet effusion-1, sagittal facet-orientation-1. Technical: feasibility to decompress without causing instability-1.5. Its reliability was ascertained by a univariate analysis. The benchmark was set at 5.5 according to the Youden Index. This was followed by a prospective study for reliability analysis between November 2011 and January 2017 of 52 patients who underwent stand-alone decompression in LDS with a minimum follow-up of 24 months. Outcomes were evaluated using the Oswestry Disability Index and the Visual Analog Scale. Interobserver variability was determined. None of the patients in the retrospective or prospective group had undergone any lumbar surgery previously.RESULTS: The mean Oswestry Disability Index and Visual Analog Scale of both the groups in the retrospective and the stand-alone decompression groups in prospective studies showed significant improvement. The interobserver reliability was high, with a ê value of 0.847.CONCLUSIONS: The proposed scoring system helps view LDS as a heterogenous condition and assists in tailoring treatment for individual patients. For a select subgroup of patients with LDS, minimally invasive decompression (unilateral laminotomy and bilateral decompression using a minimally invasive surgery tubular retractor system) without fusion is adequate.LEVEL OF EVIDENCE: Level III.

['Adult', 'Aged', 'Endoscopy', 'Female', 'Follow-Up Studies', 'Humans', 'Intervertebral Disc Degeneration', 'Intervertebral Disc Displacement', 'Lumbar Vertebrae', 'Male', 'Middle Aged', 'Retrospective Studies', 'Spinal Fusion', 'Spondylolisthesis', 'Treatment Outcome'] BACKGROUND: Conventional open surgical procedures may cause massive dissections of the spine, higher perioperative complications, prolonged hospitalization, protracted rehabilitation programs and recovery. Percutaneous endoscopic lumbar interbody fusion (PELIF) is an evolving treatment option.OBJECTIVES: To present the detailed procedure and preliminary clinical and radiologic results of PELIF for degenerative lumbar diseases.STUDY DESIGN: A retrospective cohort study.SETTING: A university affiliated tertiary hospital.METHODS: The medical records of patients with degenerative lumbar diseases who underwent PELIF between January 2016 and December 2017 were retrospectively reviewed. Surgical level, surgical time, blood loss, hospital length of stay, and perioperative complications were discussed. Patients were also evaluated for pain by the Visual Analog Scale (VAS), and functional assessment by the Oswestry Disability Index (ODI) and the 36-Item Short Form Health Survey (SF-36), including Physical Component Summary (PCS) and Mental Component Summary (MCS) preoperatively, postoperatively, and during the follow-up period.RESULTS: Thirty-nine consecutive patients (25 men and 14 women) with a mean age of 59.0 years (range, 39-77 years) were enrolled. The average surgical time was 213.8 ± 31.7 minutes (range, 185-324 minutes). Mean estimated blood loss was 25.0 ± 12.6 mL (range, 15-50 mL). At the latest follow-up visit, the VAS scores for back pain, leg pain, ODI, and SF-36 (MCS/PCS) scores improved 89.5%, 95.0%, 71.2%, and 37.5%/58%, respectively. Reoperations were performed in one patient for residual disc mass and one for misplacement of pedicle screw. Fusion was achieved in all patients.LIMITATIONS: The presented results are preliminary and should be interpreted taking the limitations into account, including nonrandomized design, relatively small sample size, and less intensive follow-up period.CONCLUSIONS: The presented PELIF technique seems to be a promising surgical alternative for the treatment of patients with specific degenerative lumbar diseases. Randomized studies with larger sample size and long-term follow-up duration are needed to validate the superiorities of this versatile surgery.KEY WORDS: Endoscopic, minimally invasive spine surgery, lumbar interbody fusion, disc herniation, spondylolisthesis.

['Aged', 'Disability Evaluation', 'Female', 'Humans', 'Laminectomy', 'Lumbar Vertebrae', 'Magnetic Resonance Imaging', 'Male', 'Postoperative Complications', 'Reoperation', 'Research Design', 'Retrospective Studies', 'Spinal Stenosis', 'Spondylolisthesis', 'Visual Analog Scale'] BACKGROUND: Most degenerative lumbar spinal stenosis (DLSS) patients primitively received the conservative treatment to control symptoms. In order to develop an optimal surgical treatment strategy, it is very significant to understand how the degenerative lumbar spondylolisthesis (DS) affects the effect of decompression in the DLSS. Thus, the aim of this current study was to explore whether the concomitant DS would affect the effect of decompression alone in the patients with DLSS.METHODS: The current study was carried out at our hospital and it was approved through our institutional review committee of General Hospital of Ningxia Medical University. During the period from January 2015 to December 2017, in our study, we identified consecutive patients who received the minimally invasive laminectomy to treat the DLSS. The inclusion criterion included radicular leg pain or neurogenic claudication with the neurological symptoms associated with DLSS syndrome, magnetic resonance imaging of the lumbar spine reveals at least 1 level of serious stenosis, the conservative treatment failed for at least 3 months, and patients agreed to provide the postoperative details. The major outcomes of this present research was Oswestry Disability Index. Secondary outcomes of this current study involved visual analog score, short form-36, surgical revision rate as well as complications.RESULTS: We assumed that previous DS possessed a negative effect on the postoperative results of the DLSS patients.TRIAL REGISTRATION: researchregistry5943.

['Aged', 'Female', 'Follow-Up Studies', 'Humans', 'Internal Fixators', 'Intervertebral Disc Degeneration', 'Lumbar Vertebrae', 'Male', 'Middle Aged', 'Retrospective Studies', 'Spinal Fusion', 'Treatment Outcome'] BACKGROUND: Studies have shown that adjacent segment degeneration (ASD) is a common complication after posterior lumbar interbody fusion (PLIF), even a second surgery is required for some patients. It remains unclear whether the non-fusion surgery can relieve ASD. Therefore, this study aims to investigate the clinical outcomes of Topping-off surgery (fusion combined with Coflex) and PLIF for degenerative lumbar disease (DLD) and the efficacy on preventing ASD.METHOD: A retrospective analysis was performed on the clinical data of 99 patients with DLD from January 2011 to December 2014, who were performed by Topping-off surgery (L4-5 PLIF + L3-4 Coflex, n = 45) or PLIF (L3-5 PLIF, n = 54). All patients included in the analysis had a minimum of 3 years of follow-up. Clinical data were used to assess the clinical efficacy, and radiographic parameters were measured for evaluation of the incidence of ASD.RESULTS: The mean ages of Topping-off group and PLIF group were 53.5 and 65.7 years old, respectively (P < 0.05). The surgical time, intraoperative blood loss, Oswestry disability index (ODI), and visual analog scale (VAS) were significantly different between the two groups (P < 0.05). Intervertebral mobility (L2-L3) of the Topping-off group was not changed significantly at 3 years after surgery than before (P > 0.05), while that of PLIF group was increased considerably (P < 0.05). As to intergroup comparison, intervertebral mobility (L2-L3) of Topping-off group was superior to those of the PLIF group (P < 0.05). Surprisingly, there was no significant difference in the general adjacent segment mobility (GASM) at L2-4 of the Topping-off group and intervertebral mobility (L2-L3) of PLIF group at 3 years after surgery (P > 0.05). Lumbar MRI at three post-operative years indicated that the modified Pfirrman grading of disc (L2-L3) in the Topping-off group was much better than that of the PLIF group (P < 0.05).CONCLUSION: This study showed that Topping-off surgery had the benefits of less invasiveness, less bleeding, and comparable clinical efficacy as PLIF for DLD. The segment with Coflex insertion undertook part of the mobility and stress in the proximal lumbar spine, which is conducive to alleviating ASD.

['Aged', 'Back Pain', 'Canada', 'Female', 'Humans', 'Lumbar Vertebrae', 'Male', 'Retrospective Studies', 'Spondylolisthesis', 'Treatment Outcome'] OF BACKGROUND DATA: Surgery for degenerative lumbar spondylolisthesis (DLS) has traditionally been indicated for patients with neurogenic claudication. Surgery improves patients' disability and lower extremity symptoms, but less is known about the impact on back pain.OBJECTIVE: To evaluate changes in back pain after surgery and identify factors associated with these changes in surgically-treated DLS.STUDY DESIGN: Retrospective review of prospectively collected data.METHODS: There were 486 consecutive patients with surgically-treated DLS who were enrolled in the Canadian Spine Outcomes Research Network prospective registry and identified for this study. Patients had demographic data, clinical information, disability (Oswestry Disability Index), and back pain rating scores collected prospectively at baseline, and 12 months follow-up RESULTS: Of the 486 DLS patients, 376 (77.3%) were successfully followed at 12 months. Mean age at baseline was 66.7 (standard deviation [SD] 9.2) years old, and 63% were female. Back pain improved significantly at 12 months, compared with baseline (p<.001). Improvement in Numeric Rating Scale (NRS)-back pain ratings was on average 2.97 (SD 2.5) points at one year and clinically significant improvement in back pain was observed in 75% of patients (minimal clinically important difference (MCID) NRS-Pain 1.2 points). Multivariable logistic regression revealed five factors associated with meeting MCID NRS-back pain at 12 month follow up: higher baseline back pain, better baseline physical function (higher SF-12 Physical Component Score), symptoms duration less than 1 to 2 years, and having no intraoperative adverse events.CONCLUSIONS: Back pain improved significantly for patients treated surgically for DLS at 1-year follow-up.


In [ ]:
print(temp)

['Context information is below: ABSTRACT: Case-control studies by examining the lumbar spine computed tomography (CT) findings focusing on the spinous processes."Passing spine" was defined as a lumbar degenerative change observed on CT images. In contrast, kissing spine, which is also an image finding, has been acknowledged as an established clinical condition. Therefore, we compared the passing spine group and the kissing spine group to investigate whether the 2 groups belong to a similar disease group; this would help explain the clinical and imaging characteristics of patients with passing spine.Previous studies have described the gradual increase in the height and thickness of the lumbar vertebral spinous processes that can occur in individuals aged >40\u200ayears, and reported that this progressive degeneration can lead to a condition termed "kissing spine."We examined the CT imaging of 373 patients with lumbar spinal disease and divided patients into 2 groups, the kissing spine (K) group and the passing spine (P) group, and compared the clinical (age, sex, presence/absence of lower extremity pain) and imaging data (localization of kissing or passing spine, intervertebral disc height at the level of kissing or passing spine, lumbar lordosis (LL) angle, presence/absence of vacuum phenomenon (VP) in the intervertebral discs and spondylolisthesis at the level of kissing or passing spine between the 2 groups.Compared with patients with kissing spine, patients with passing spine had an increased incidence of lower extremity pain, lower intervertebral disc height at the level of passing spine, relatively static LL, and VP commonly observed in the intervertebral discs at the level of passing spine.Because the clinical and imaging characteristics of patients with passing spine are different from those of patients with kissing spine, passing spine might be a pathological condition distinct from kissing spine. Given the context information above I want you to think step by step to answer the query in a crisp manner, incase you don\'t know the answer say \'I don\'t know!\' Query: Lumbar Spine Degenerative? Answer:', "Context information is below: BACKGROUND: The lateral lumbar interbody fusion (LLIF) was a revolutionary approach devised by Luiz Pimenta that allowed the surgeon to access the lumbar spine through the major psoas muscle. Although the traditional LLIF had enabled enormous advances, the technique has its drawbacks. A new concept to perform the traditional LLIF has been proposed, with the patient being prone to decubitus with slightly extended legs. Our study aims to analyze the early outcomes of patients who had undergone the prone transpsoas (PTP) for degenerative spine pathologies including the L4/5 level.METHODS: This study was multicentric, retrospective, nonrandomized, noncomparative, and observational. Only participants who received PTP in L4/5, with no more than 3 levels of intersomatics and fixation no further than S1, were included. The primary outcomes were the onset of new neurologic deficits and postoperative complications. Also, surgery details, such as blood loss and surgery duration, were measured. Neurologic deficits were accessed at the postoperative visit, which ranged from 7 to 14 days after surgery.RESULTS: Twenty-seven patients fulfilled the inclusion and exclusion criteria, with the majority receiving PTP only in L4/5 (66.6%). The mean surgery time was 182, with 29 minutes of mean transpsoas time. Of the patients, only 1 presented the onset of a motor deficit, while 3 patients presented a new sensory deficit. Five complications occurred, none intraoperative and 5 postoperative, with only 1 directly correlated with the access.CONCLUSIONS: The prone transpsoas is safe and feasible for approaching the L4/5 disk, presenting with a low rate of complication and new-onset neurologic deficits. Given the context information above I want you to think step by step to answer the query in a crisp manner, incase you don't know the answer say 'I don't know!' Query: Lumbar Spine Degenerative? Answer:", "Context information is below: Elective lumbar surgery for common degenerative lumbar spine pathology has been consistently demonstrated to have excellent outcomes by multiple validated measures and improves patient quality of life. The rate of complication is low but not unavoidable; there is an increasing recognition of risk factors that can be mitigated to decrease complication rates. When complications occur, prompt recognition and management may minimize deleterious effects on patient outcome. There are considerations for identifying risk factors and, when possible, minimizing them and general strategies for identifying and managing common complications in lumbar spine surgery. Given the context information above I want you to think step by step to answer the query in a crisp manner, incase you don't know the answer say 'I don't know!' Query: Lumbar Spine Degenerative? Answer:", "Context information is below: Low back pain due to lumbar Degenerative Disc Disease (DDD) is one of the most common causes of disability and morbidity, particularly among older adults. Current research efforts in lumbar DDD management are shifting towards identifying and correcting the pathology in intervertebral discs without any external manipulation. Herein, we present a systematic review of current literature regarding regenerative treatments for lumbar DDD. An electronic search of databases including PubMed, Ovid/MEDLINE, Cochrane and Scopus was conducted for articles in all available years. Studies that investigated treatment for discogenic pain in lumbar DDD, including any type of stem cell or bone marrow concentrate as the treatment agent and studies that report both baseline and follow-up pain and Oswestry Disability Index (ODI) scores were included in the review. Changes in pain and ODI scores were calculated for 3-month, 6-month and 12-month periods. Six studies with a total of 93 patients were evaluated. Mean (SD) age of the pooled sample was 40.0(8.1) and 39.5% (32/81) of patients were female. Pain improvement was reported in 38.8% of patients at 3-month, 40.8% at 6-month and 44.1% at 12-month follow-up. Average improvement in ODI score for 3-month, 6-month and 12-month follow-ups was calculated to be 24.0, 26.5 and 25.7, respectively. Regenerative treatments are being increasingly employed across all spectrums of medicine. Review of six single arm studies revealed a potential positive impact in the preliminary results. However, these promising 'preliminary' results should not be interpreted as the definite treatment and should be validated with further prospective studies. Given the context information above I want you to think step by step to answer the query in a crisp manner, incase you don't know the answer say 'I don't know!' Query: Lumbar Spine Degenerative? Answer:", "Context information is below: STUDY DESIGN: A prospective cohort.OBJECTIVE: The objective of this study was to develop a scoring system for lumbar degenerative spondylolisthesis (LDS) that would guide decision-making.BACKGROUND: The management protocol for LDS has been under debate, with no guidelines. Most studies oversimplify LDS as a homogenous entity.MATERIALS AND METHODS: A retrospective analysis of 131 patients who underwent surgery for LDS between July 2007 and October 2011 with a minimum follow-up of 3 years was carried out on the basis of clinical, radiologic, and technical factors. A scoring system was conceptualized. Clinical: back pain score-2, age younger than 70 years-1, high-demand activity-1. Radiologic: segmental kyphosis-1.5, segmental dynamic translation-1, disk height >50% of adjacent level-1, facet effusion-1, sagittal facet-orientation-1. Technical: feasibility to decompress without causing instability-1.5. Its reliability was ascertained by a univariate analysis. The benchmark was set at 5.5 according to the Youden Index. This was followed by a prospective study for reliability analysis between November 2011 and January 2017 of 52 patients who underwent stand-alone decompression in LDS with a minimum follow-up of 24 months. Outcomes were evaluated using the Oswestry Disability Index and the Visual Analog Scale. Interobserver variability was determined. None of the patients in the retrospective or prospective group had undergone any lumbar surgery previously.RESULTS: The mean Oswestry Disability Index and Visual Analog Scale of both the groups in the retrospective and the stand-alone decompression groups in prospective studies showed significant improvement. The interobserver reliability was high, with a ê value of 0.847.CONCLUSIONS: The proposed scoring system helps view LDS as a heterogenous condition and assists in tailoring treatment for individual patients. For a select subgroup of patients with LDS, minimally invasive decompression (unilateral laminotomy and bilateral decompression using a minimally invasive surgery tubular retractor system) without fusion is adequate.LEVEL OF EVIDENCE: Level III. Given the context information above I want you to think step by step to answer the query in a crisp manner, incase you don't know the answer say 'I don't know!' Query: Lumbar Spine Degenerative? Answer:", "Context information is below: BACKGROUND: Conventional open surgical procedures may cause massive dissections of the spine, higher perioperative complications, prolonged hospitalization, protracted rehabilitation programs and recovery. Percutaneous endoscopic lumbar interbody fusion (PELIF) is an evolving treatment option.OBJECTIVES: To present the detailed procedure and preliminary clinical and radiologic results of PELIF for degenerative lumbar diseases.STUDY DESIGN: A retrospective cohort study.SETTING: A university affiliated tertiary hospital.METHODS: The medical records of patients with degenerative lumbar diseases who underwent PELIF between January 2016 and December 2017 were retrospectively reviewed. Surgical level, surgical time, blood loss, hospital length of stay, and perioperative complications were discussed. Patients were also evaluated for pain by the Visual Analog Scale (VAS), and functional assessment by the Oswestry Disability Index (ODI) and the 36-Item Short Form Health Survey (SF-36), including Physical Component Summary (PCS) and Mental Component Summary (MCS) preoperatively, postoperatively, and during the follow-up period.RESULTS: Thirty-nine consecutive patients (25 men and 14 women) with a mean age of 59.0 years (range, 39-77 years) were enrolled. The average surgical time was 213.8 ± 31.7 minutes (range, 185-324 minutes). Mean estimated blood loss was 25.0 ± 12.6 mL (range, 15-50 mL). At the latest follow-up visit, the VAS scores for back pain, leg pain, ODI, and SF-36 (MCS/PCS) scores improved 89.5%, 95.0%, 71.2%, and 37.5%/58%, respectively. Reoperations were performed in one patient for residual disc mass and one for misplacement of pedicle screw. Fusion was achieved in all patients.LIMITATIONS: The presented results are preliminary and should be interpreted taking the limitations into account, including nonrandomized design, relatively small sample size, and less intensive follow-up period.CONCLUSIONS: The presented PELIF technique seems to be a promising surgical alternative for the treatment of patients with specific degenerative lumbar diseases. Randomized studies with larger sample size and long-term follow-up duration are needed to validate the superiorities of this versatile surgery.KEY WORDS: Endoscopic, minimally invasive spine surgery, lumbar interbody fusion, disc herniation, spondylolisthesis. Given the context information above I want you to think step by step to answer the query in a crisp manner, incase you don't know the answer say 'I don't know!' Query: Lumbar Spine Degenerative? Answer:", "Context information is below: BACKGROUND: Most degenerative lumbar spinal stenosis (DLSS) patients primitively received the conservative treatment to control symptoms. In order to develop an optimal surgical treatment strategy, it is very significant to understand how the degenerative lumbar spondylolisthesis (DS) affects the effect of decompression in the DLSS. Thus, the aim of this current study was to explore whether the concomitant DS would affect the effect of decompression alone in the patients with DLSS.METHODS: The current study was carried out at our hospital and it was approved through our institutional review committee of General Hospital of Ningxia Medical University. During the period from January 2015 to December 2017, in our study, we identified consecutive patients who received the minimally invasive laminectomy to treat the DLSS. The inclusion criterion included radicular leg pain or neurogenic claudication with the neurological symptoms associated with DLSS syndrome, magnetic resonance imaging of the lumbar spine reveals at least 1 level of serious stenosis, the conservative treatment failed for at least 3 months, and patients agreed to provide the postoperative details. The major outcomes of this present research was Oswestry Disability Index. Secondary outcomes of this current study involved visual analog score, short form-36, surgical revision rate as well as complications.RESULTS: We assumed that previous DS possessed a negative effect on the postoperative results of the DLSS patients.TRIAL REGISTRATION: researchregistry5943. Given the context information above I want you to think step by step to answer the query in a crisp manner, incase you don't know the answer say 'I don't know!' Query: Lumbar Spine Degenerative? Answer:", "Context information is below: BACKGROUND: Studies have shown that adjacent segment degeneration (ASD) is a common complication after posterior lumbar interbody fusion (PLIF), even a second surgery is required for some patients. It remains unclear whether the non-fusion surgery can relieve ASD. Therefore, this study aims to investigate the clinical outcomes of Topping-off surgery (fusion combined with Coflex) and PLIF for degenerative lumbar disease (DLD) and the efficacy on preventing ASD.METHOD: A retrospective analysis was performed on the clinical data of 99 patients with DLD from January 2011 to December 2014, who were performed by Topping-off surgery (L4-5 PLIF + L3-4 Coflex, n\u2009=\u200945) or PLIF (L3-5 PLIF, n\u2009=\u200954). All patients included in the analysis had a minimum of 3\xa0years of follow-up. Clinical data were used to assess the clinical efficacy, and radiographic parameters were measured for evaluation of the incidence of ASD.RESULTS: The mean ages of Topping-off group and PLIF group were 53.5 and 65.7\u2009years old, respectively (P\xa0<\u20090.05). The surgical time, intraoperative blood loss, Oswestry disability index (ODI), and visual analog scale (VAS) were significantly different between the two groups (P\xa0<\u20090.05). Intervertebral mobility (L2-L3) of the Topping-off group was not changed significantly at 3\xa0years after surgery than before (P\u2009>\u20090.05), while that of PLIF group was increased considerably (P\u2009<\u20090.05). As to intergroup comparison, intervertebral mobility (L2-L3) of Topping-off group was superior to those of the PLIF group (P\u2009<\u20090.05). Surprisingly, there was no significant difference in the general adjacent segment mobility (GASM) at L2-4 of the Topping-off group and intervertebral mobility (L2-L3) of PLIF group at 3\xa0years after surgery (P\u2009>\u20090.05). Lumbar MRI at three post-operative years indicated that the modified Pfirrman grading of disc (L2-L3) in the Topping-off group was much better than that of the PLIF group (P\u2009<\u20090.05).CONCLUSION: This study showed that Topping-off surgery had the benefits of less invasiveness, less bleeding, and comparable clinical efficacy as PLIF for DLD. The segment with Coflex insertion undertook part of the mobility and stress in the proximal lumbar spine, which is conducive to alleviating ASD. Given the context information above I want you to think step by step to answer the query in a crisp manner, incase you don't know the answer say 'I don't know!' Query: Lumbar Spine Degenerative? Answer:", "Context information is below: OF BACKGROUND DATA: Surgery for degenerative lumbar spondylolisthesis (DLS) has traditionally been indicated for patients with neurogenic claudication. Surgery improves patients' disability and lower extremity symptoms, but less is known about the impact on back pain.OBJECTIVE: To evaluate changes in back pain after surgery and identify factors associated with these changes in surgically-treated DLS.STUDY DESIGN: Retrospective review of prospectively collected data.METHODS: There were 486 consecutive patients with surgically-treated DLS who were enrolled in the Canadian Spine Outcomes Research Network prospective registry and identified for this study. Patients had demographic data, clinical information, disability (Oswestry Disability Index), and back pain rating scores collected prospectively at baseline, and 12 months follow-up RESULTS: Of the 486 DLS patients, 376 (77.3%) were successfully followed at 12 months. Mean age at baseline was 66.7 (standard deviation [SD] 9.2) years old, and 63% were female. Back pain improved significantly at 12 months, compared with baseline (p<.001). Improvement in Numeric Rating Scale (NRS)-back pain ratings was on average 2.97 (SD 2.5) points at one year and clinically significant improvement in back pain was observed in 75% of patients (minimal clinically important difference (MCID) NRS-Pain 1.2 points). Multivariable logistic regression revealed five factors associated with meeting MCID NRS-back pain at 12 month follow up: higher baseline back pain, better baseline physical function (higher SF-12 Physical Component Score), symptoms duration less than 1 to 2 years, and having no intraoperative adverse events.CONCLUSIONS: Back pain improved significantly for patients treated surgically for DLS at 1-year follow-up. Given the context information above I want you to think step by step to answer the query in a crisp manner, incase you don't know the answer say 'I don't know!' Query: Lumbar Spine Degenerative? Answer:", "Context information is below: OBJECTIVE: To assess the clinical efficacy and share the technique notes of Wiltse Approach TLIF for the treating single segment degenerative lumbar spinal disease.METHOD: In this retrospective controlled study, 780 patients with single segment degenerative lumbar disease who were operated in our hospital from January 2016 to December 2020 were analyzed retrospectively. The patients were randomly assigned to Wiltse approach group (group A, 410 cases) and conventional open approach group (group B, 370 cases). Patient's assessment of pain and disability were evaluated by the visual analogue scale (VAS) and the Oswestry disability index (ODI) before and after surgery. The incision length, operative time, exposure time, intraoperative blood loss, hidden blood loss, time to ambulation, total length of hospitalization, serum creatine kinase, X-rays, CT and MRI were also evaluated.RESULTS: There were no differences in sex, age, pre-operative ODI score, VAS score between the two groups (P\u2009>\u20090.05). The Wiltse approach group had a shorter incision length with 7.69\u2009±\u20090.44\u2009cm compared to the conventional group with 11.13\u2009±\u20090.36\u2009cm (P\u2009<\u20090.01). The average operative time was 119.20\u2009±\u200914.64\u2009min with exposure time of 16.20\u2009±\u20093.42\u2009min in the Wiltse approach group and 145.65\u2009±\u200916.98\u2009min with 29.20\u2009±\u20093.42\u2009min in the conventional group (P\u2009<\u20090.05, P\u2009<\u20090.01). Comparing the intraoperative blood loss, hidden blood loss, serum creatine kinase, time to ambulation, total length of hospitalization, the Wiltse approach group was less than the conventional open approach group (P < 0.05). The VAS score of the t

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer
device = "cuda" # the device to load the model onto

model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2.5-7B-Instruct", device_map="auto")
# tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-7B-Instruct", device_map="auto")
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/all-MiniLM-L6-v2', device_map="auto")

# model = AutoModelForCausalLM.from_pretrained(
#     "meta-llama/Llama-3.1-405B-FP8",
#     device_map="auto",
#     token="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"  # Add your token here
# )
# tokenizer = AutoTokenizer.from_pretrained(
#     "meta-llama/Llama-3.1-405B-FP8",
#     token="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"  # Add your token here
# )

prompt = temp[0]

messages = [{"role": "user", "content": prompt}]

text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

model_inputs = tokenizer([text], return_tensors="pt").to(device)

# generated_ids = model.generate(model_inputs.input_ids, max_new_tokens=512, do_sample=True)
generated_ids = model.generate(model_inputs.input_ids, max_new_tokens=52, do_sample=True)

generated_ids = [output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/4 [00:00<?, ?it/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/3.95G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/3.56G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

WARNING:accelerate.big_modeling:Some parameters are on the meta device because they were offloaded to the cpu.

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

In [ ]:
print(response)

Based on the abstract provided, lumbar spine degenerative changes can manifest in two forms: passing spine and kissing spine. Both are observed on CT images and are related to degenerative changes in the lumbar vertebrae, but they have distinct characteristics:

1

In [ ]:
# Caculate BLEU score
import nltk
from nltk.translate.bleu_score import sentence_bleu
nltk.download('punkt')

# HyDE

In [ ]:
# from transformers import pipeline

# generator = pipeline(model="HuggingFaceH4/zephyr-7b-beta")
# # Zephyr-beta is a conversational model, so let's pass it a chat instead of a single string
# generator([{"role": "user", "content": "What is Lumber Spine Degeneration?"}], do_sample=False, max_new_tokens=2)

In [ ]:
# generator([{"role": "user", "content": "What is Lumber Spine Degeneration?"}], do_sample=False, max_new_tokens = 200)

In [ ]:
# from transformers import AutoModelForCausalLM, AutoTokenizer
# device = "cuda" # the device to load the model onto
# ref_model = AutoModelForCausalLM.from_pretrained("BioMistral/BioMistral-7B", device_map="auto")
# tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-7B-Instruct", device_map="auto")

In [ ]:
# messages = [
#     {"role": "user", "content": "What is Lumbar Spine Degenerative?"}
# ]

# encodeds = tokenizer.apply_chat_template(messages, return_tensors="pt")

# model_inputs = encodeds.to('cuda')

# generated_ids = ref_model.generate(model_inputs, max_new_tokens=1000, do_sample=True)
# decoded = tokenizer.batch_decode(generated_ids)
# print(decoded[0])

In [ ]:
# Inspect the response
temp = []
for o in ref_response.objects:
    print(
        o.properties["meshMajor"], o.properties["abstractText"]
    )
    temp.append(f"Context information is below: {o.properties['abstractText']} Given the context information above I want you to think step by step to answer the query in a crisp manner, incase you don't know the answer say 'I don't know!' Query: {query_text} Answer:")  # Print the title and release year (note the release date is a datetime object)
    print(
        # f"Distance to query: {o.metadata.distance:.3f}\n"
    )  # Print the distance of the object from the query

client.close()

In [ ]:
prompt = temp[0]

messages = [{"role": "user", "content": prompt}]

text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

model_inputs = tokenizer([text], return_tensors="pt").to(device)

# generated_ids = model.generate(model_inputs.input_ids, max_new_tokens=512, do_sample=True)
generated_ids = model.generate(model_inputs.input_ids, max_new_tokens=52, do_sample=True)

generated_ids = [output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]